name: Film Botu Calistir

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik çalışır
  workflow_dispatch: # Senin manuel olarak başlatmanı sağlar

permissions:
  contents: write # GitHub'ın dosyaları depona kaydetmesi için şarttır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        run: pip install requests beautifulsoup4

      - name: Botu Calistir
        run: python fulhdfilm.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Yeni dosyaları ve klasörü Git takibine al
          git add data/
          git add data/*.json
          
          # Eğer değişiklik varsa commit yap, yoksa hata vermeden geç
          git commit -m "Film verileri güncellendi (1113 Sayfa)" || echo "Değişiklik yok."
          
          # Verileri depoya gönder
          git push
